### ISSUE TITLE
Pending Claim still returning the same value even when the amount is claimed successfully

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#101]
**Describe the bug**
Pending Claim still returning the same value even when the amount is claimed successfully. Tried refreshing several times but still the same.
PS : After 10 mins, now it shows correctly.

**Expected behavior**
After claiming all the rewards, the pending rewards should be 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/36991769/97777318-6dbb4a80-1b95-11eb-90a1-f0796b5723bf.png)

**Comment by venkateshsys** [comment]
@bhavya-plotx what is the user address here?

**Comment by bhavya-plotx** [comment]
@ankit5902 Please share your wallet address.

**Comment by ankit5902** [comment]
0x7Ba7f68AC3929a2357123440e2DB79d5e6767895

**Comment by venkateshsys** [comment]
@ankit5902 Are you sure the address given is correct? It does not match the total staked value.

![image](https://user-images.githubusercontent.com/48546261/97810742-18b62c00-1c9c-11eb-8094-2087eda24824.png)

**Comment by ankit5902** [comment]
Oops, I gave my address by mistake. Wait I am sending the correct one.
Here it is : 0x62eEF23AA342d688008A39E088026b1D9f1a3dcc
Sorry!

**Comment by venkateshsys** [comment]
@ankit5902 It matches, the issue has been solved also, Have a look and close this issue once confirmed.

![image](https://user-images.githubusercontent.com/48546261/97839172-a1b67d00-1d07-11eb-93c0-dad9fbdc130b.png)

**Comment by ankit5902** [comment]
The issue has been resolved.
