### ISSUE TITLE
"How to use" does not shows up sometimes

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#102]
**Describe the bug**
"How to use" does not shows up sometimes in Daily Weekly Market. Check screenshot to get better understanding.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://app.plotx.io'
2. Check the attached screenshot "How to use is not showing in Daily or Weekly Market page.

**Expected behaviour**
"How to use" should be visible in every market.

**Screenshots**
![image](https://user-images.githubusercontent.com/36991769/97777496-955ee280-1b96-11eb-8998-557cf83a356f.png)

**Comment by bhavya-plotx** [comment]
@ankitnirwal Please look into this. 
![Uploading image.png…]()

**Comment by SamDevGH** [comment]
![image](https://user-images.githubusercontent.com/66849800/103353010-b3c95780-4acd-11eb-9df7-a2ce2f38b1b1.png)

The issue is still persisting.
