### ISSUE TITLE
Notifications doesn't shows up when scrolling down

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#103]
**Describe the bug**
When we are at bottom of the page, the notifications aren't shown until we go to top of the page.

**To Reproduce**
1. Go to 'https://app.plotx.io'
2. Scroll down to 'bottom or middle of the page'
4. When someone makes prediction, the notifications doesn't shows up until we scroll to top of the page.

**Expected behavior**
Notifications should be visible from anywhere in the page - top, middle or bottom.

**Comment by ankitnirwal** [comment]
@ankit5902 It works fine here, please check once and 
![Uploading Screenshot (6).png…]()
close the issue.

**Comment by ankitnirwal** [comment]
@ankit5902 It works fine here, please check once and close the issue.
![Screenshot (6)](https://user-images.githubusercontent.com/61899399/98209283-a9bf2880-1f64-11eb-94b3-82f53fd0358b.png)

**Comment by ankit5902** [comment]
Seems now it is working fine, but faced this issue twice.
