### ISSUE TITLE
Several predictions that were placed in the market are not showing in the market leaderboard

### ISSUE THREAD

**Issue by Samagra-Dev** [plotx/smart-contracts#105]
> <div class="intercom-container"><img src="https://downloads.intercomcdn.com/i/o/261771542/d907667d522725a78468113e/image.png"></div>

Market address - 0xD72F9e3C6a9115C19A760Ce330ee0F935B56fF5e

The total participation amount might also be wrong. Please check that as well.
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/e3g56a54/respond/inbox/all/conversations/284) when this issue is closed.

**Comment by venkateshsys** [comment]
@Samagra-Dev Issue has been resolved

![image](https://user-images.githubusercontent.com/48546261/97899542-73648c00-1d5f-11eb-84c3-59decd433bce.png)
