### ISSUE TITLE
Have some functionality that would give users more control over the pending reward trx

### ISSUE THREAD

**Issue by Samagra-Dev** [plotx/smart-contracts#106]
We can see how much pending amount can be claimed from the "my account" page, but, we cannot:

- See how many markets is that sum coming from. This leads to me not having a clear picture of how much gas am I spending per market claim.

- See how much ETH &/or PLOT am I getting from which market. When you don't claim your pending amount for a long time, you lose track of how much ETH &/or PLOT you're supposed to receive and from which market.

- Have any control over the trx itself. For example, it may be that a part of the pending amount is coming from a market from where I am getting a tiny amount of ETH &/or PLOT. Now, if I have only a single button to claim the pending amount then I'll be forced to spend ETH to get this tiny amount within the same trx and that might not make financial sense.

Now, if we could have some functionality that would enable users to not only see how many markets is their pending amount coming from but also which particular markets are they getting their pending rewards from, how much ETH &/or PLOT are they getting from these markets, and select which rewards do they want to claim in the trx when they click on the Claim button, then:

- Users who don't know about the reason for high claim gas cost will get to know that since their reward is coming from many different market addresses within the same trx, the gas cost is relatively higher (at least for now).

- Users can have a clearer picture of the real gas per market that they are paying for getting their rewards. 

- Users can deselect the markets which are not paying enough (at the moment) to cover the GAS cost that'll be spent to claim those rewards.

**Comment by bhavya-plotx** [comment]
I think this will be a welcome change for the community. It has been a constant complaint that gas costs for claiming rewards are very high. According to the anecdotal computations, it costs about 120,000 gas on average per market to claim rewards. Even at an extremely low price of 20 gwei, it would still cost about $1 to claim the rewards. 

I think the easiest solution is to add a claim reward button next to each market in the "My Accounts" table. The main claim button uptop can clearly spell out this transaction will trigger reward claim from all markets: 

![image](https://user-images.githubusercontent.com/73012963/97998813-9438ea00-1e10-11eb-8551-44b3e3830840.png)

**Comment by Samagra-Dev** [comment]
No need for this now as the new version solves all these issues.

**Comment by Samagra-Dev** [comment]
No need for this now as the new version solves all these issues
