### ISSUE TITLE
Issue with filtering out and switiching b/w Hourly, Daily and Weekly in "My Account" tab

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#107]
**Describe the bug**
**Issue 1 :** I've come across a couple of display glitches today.
When filtering my predictions on the "My Account" tab, if I set it to filter by "In Settlement" it won't display any markets even though when I display all I can see that I have 2  prediction markets currently in the "In Settlement" Phase.

**Issue2** : The other issue I've noticed is when I am looking at my predictions, I have the options to look at Hourly, Daily or Weekly. The issue comes when I'm looking through my list of Daily predictions and I am displaying 10 records per page if I go to page 2 and then switch to display a different market, Hourly or Weekly, then page 2 of that market is displayed rather than displaying page 1. I'm not sure that this is actually an issue except that I don't currently have enough predictions in the hourly market to have any records on page 2, so it just displays a blank page and there isn't an option to go back to page 1. I have to go back to the Daily tab, click page 1 and then go back to the hourly tab.

**Expected behaviour**
**Issue 1 :** Filtering the prediction in My account tab should show corresponding prediction like predictions "In Settlement" should show "In Settlement" predictions, predictions in Cooling should show "In Cooling" predictions etc. an so on..

**Issue 2 :** "My Account" tab - When on page 2 in Hourly BTCUSD market, if switching to Daily BTCUSD market (provided the prediction has transactions only for page 1) should switch to page 1 instead of page 2 for Daily Market. Similarly switching back and forth for both the market.

**Additional Comments**
Post Fix : This needs to be fixed and cross checked thoroughly in every market like Hourly, Daily, Weekly and BTC and ETH.

**Comment by KushalJaisinghani** [comment]
I have fixed issue 1
