### ISSUE TITLE
Negative amount shown in Pending Rewards

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#108]
**Describe the bug**
Negative amount being shown in pending rewards

**To Reproduce**

1. Go to https://beta.plotx.io/userAccount/ETH-USD/Hourly/0x6BF32Be85a8d6893AEb618A7fd091F6a70745f33'
2. See error wrt negative PLOTs to claim

**Expected behaviour**
After claiming my rewards, the pending rewards should be 0 or a positive number.

**Screenshots**

![image](https://user-images.githubusercontent.com/36991769/98259310-f9731380-1fa7-11eb-9f38-68cbf6991451.png)

**Comment by venkateshsys** [comment]
Issue has been resolved @ankit5902 

![image](https://user-images.githubusercontent.com/48546261/98333511-ee12fd00-2026-11eb-8932-f6baecf0d620.png)

**Comment by ankit5902** [comment]
Issue resolved and confirmed from the user too.
