### ISSUE TITLE
Issue while using PlotX in MetaMask dApp Browser (Mobile App)

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#109]
**Describe the bug**
Unable to connect PlotX via MetaMask Browser (Mobile App). The page refreshes and we see the same wallet connection screen. It works well while using external browsers like Chrome, Brave etc, but issue arises when using MetaMask dApp Browser (iOS).

**To Reproduce**
1. Open 'MetaMask Browser (Mobile App)'
2. Go to 'https://app.plotx.io or https://liquidity.plotx.io or https://referral.plotx.io'
3. Connect MetaMask Wallet.
4. It refreshes but doesn't connects.

**Expected behavior**
On selecting MetaMask while connecting wallet, the Wallet should connect.

**Smartphone (please complete the following information):**
 - MetaMask iOS App 

**Additional context**
Also need to confirm if there's issue with MetaMask Android App or only MetaMask iOS App.

**Comment by ankitnirwal** [comment]
closing this, already listed this in the issues
