### ISSUE TITLE
[Short description of bug]



### ISSUE THREAD

**Issue by paulstone198** [plotx/smart-contracts#110]
Kwoz:
The reward claiming function doesn't seem to be working for me at the moment. I have tried 3 times over the last couple of hours to claim my pending rewards but each time the transaction confirms nothing happens. 
The markets are settled that the rewards came from. Any ideas why claiming isn't working?

I've spent about $18 on gas fees so far. 😬

Telegram username: @kwozymoto

**Comment by bhavya-plotx** [comment]
As captured in https://github.com/plotx/smart-contracts/issues/111
