### ISSUE TITLE
User unable to claim all of his PLOT from "Pending Claim"

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#111]
**Describe the bug**
"I've got just over 700 PLOT available to claim, I've tried to claim it twice with successful transaction but nothing seems to happen."
"I just did another claim and the majority of my pending rewards were paid out but I still have 718 PLOT that show as pending in my PlotX account."

**Etherscan Link :** https://etherscan.io/tx/0x1a8bdf85d35fd1b2ef36c663ecf4c928fb5a20f875895f15c056a4c6fa00981b

**To Reproduce**
1. Go to 'https://beta.plotx.io/userAccount/BTC-USD/Hourly/0xe74b3696c6d93716ce01472125be3b9c74aa378b'
2. Check pending Claim
3. The user is not able to claim all of his PLOT (i.e 718 PLOT is not being claimed)

**Expected behavior**
User should be able to claim all his PLOT from the pending Claim.

**Comment by ankit5902** [comment]
Etherscan Link : https://etherscan.io/tx/0x1a8bdf85d35fd1b2ef36c663ecf4c928fb5a20f875895f15c056a4c6fa00981b

**Comment by ankit5902** [comment]
I'm still having issues claiming rewards. I have 1165 PLOT pending that I am unable to claim. The markets have fully settled hours ago (some of them days ago) yet when I try to claim nothing happens. The transaction was successful but the rewards aren't actually claimed. https://etherscan.io/tx/0x04738e4655f5255b108a68afbde8c56c67536bc109dfc24060563b71447b8ffb

**Comment by bhavya-plotx** [comment]
Kwoz:
The reward claiming function doesn't seem to be working for me at the moment. I have tried 3 times over the last couple of hours to claim my pending rewards but each time the transaction confirms nothing happens.
The markets are settled that the rewards came from. Any ideas why claiming isn't working?

I've spent about $18 on gas fees so far. 😬

Telegram username: @kwozymoto

**Comment by venkateshsys** [comment]
@ankit5902 @bhavya-plotx Manually transferred PLOTs and Just updated on UI side for the pending claims
