### ISSUE TITLE
[Short description of bug]

### ISSUE THREAD

**Issue by paulstone198** [plotx/smart-contracts#112]
Having difficulty in claiming rewards

I'm still having issues claiming rewards. I have 1165 PLOT pending that I am unable to claim. The markets have fully settled hours ago (some of them days ago) yet when I try to claim nothing happens. The transaction was successful but the rewards aren't actually claimed.
https://etherscan.io/tx/0x04738e4655f5255b108a68afbde8c56c67536bc109dfc24060563b71447b8ffb

**Comment by bhavya-plotx** [comment]
Captured in https://github.com/plotx/smart-contracts/issues/111
