### ISSUE TITLE
Issue with 'Predict Now' button on Leaderboard

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#113]
**Describe the bug**
When you are in a Leaderboard section of any market, except hourly ETH and click the button "Predict Now" the system forwards you in hourly ETH market by default. This is super inconvenient.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Leaderboard'
2. Click on 'Daily or Weekly of BTC or ETH market' or 'Hourly of BTC market'
3. Select any market which is 'Live'
4. Click 'Predict Now'
5. It redirects to Hourly ETH Market instead of that particular market.

**Expected behavior**
When clicking 'Predict Now' on Daily BTC market, it should redirect to Daily BTC Market instead of Hourly ETH market.

**Screenshots**

![image](https://user-images.githubusercontent.com/36991769/98543109-fa61b900-22b7-11eb-930a-cc7a82af4027.png)

**Comment by ankitnirwal** [comment]
done, closing this issue
