### ISSUE TITLE
Market not yet settled for ETHUSD Nov 9, 7:30 PM

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#115]
**Describe the bug**
ETHUSD Market at Nov 9, 07:30 PM (IST) is still not settled.

**To Reproduce**
1. Go to ‘https://app.plotx.io/leaderboard/0x37bd981c29dc881836443502ba79a5cca008e4e9‘
2. The market is still not settled.

**Expected behavior**
Market should have been settled by now since it is more than 18 hours now.

**Screenshots**

![218E81A2-1BAB-4EF0-B890-91A31EC2C9AB](https://user-images.githubusercontent.com/36991769/98657532-fe4d1400-2367-11eb-828c-f86f211a7104.jpeg)

**Comment by venkateshsys** [comment]
Market was already closed @ankit5902
