### ISSUE TITLE
Need the timer to start reflecting minutes in Weekly markets in the last hour of the market

### ISSUE THREAD

**Issue by Samagra-Dev** [plotx/smart-contracts#116]
![image](https://user-images.githubusercontent.com/66849800/98679990-cacdb200-2386-11eb-8775-9fa9d8af6a74.png)

A minor UI improvement - During the last hour of weekly markets, the timer shows 0 days and 0 hours. Can we have it show time like in hourly markets during this time?

**Comment by ankitnirwal** [comment]
done. closing this issue
