### ISSUE TITLE
Market not settled. 

### ISSUE THREAD

**Issue by divij-sood** [plotx/smart-contracts#118]
**Describe the bug**
ETH/USD at Nov 14 2020 11:30 am  is still not settled.

**To Reproduce**

Go to https://beta.plotx.io/leaderboard/0x3de33513be07961522233d53b57f96c21f545e04
The market is still not settled.

**Expected behavior**
Market should have been settled by now since it is more than 2 days now.

**Screenshots**
![image](https://user-images.githubusercontent.com/73034074/99261683-0d8a0100-2843-11eb-855f-afbdcffb3b29.png)

**Comment by venkateshsys** [comment]
Issue has been resolved @divij-sood @bhavya-plotx 

![image](https://user-images.githubusercontent.com/48546261/99265944-4678a480-2848-11eb-8cf8-b25c85fe87a7.png)
