### ISSUE TITLE
User claimed bPLOT but showing only 2.5 bPLOT in MetaMask

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#121]
**Describe the bug**
User claimed bPLOT successfully and it does reflect 250 bPLOT in Etherscan but shows only 2.5 bPLOT in MetaMask.

Etherscan : https://etherscan.io/tx/0xab300e14d46b8cf8cea3567e2d97cbf6add2445fb3e3728291fc4a49acfbc128
ERC Wallet Address : 0x32cDD1efa1f99AA759AF037750FDAD5174763698

Telegram : @peterdavid85

**Expected behavior**
It should be showing 250 bPLOT in MetaMask.

**Screenshots**

![image](https://user-images.githubusercontent.com/36991769/99640645-31ca2580-2a6f-11eb-9200-bc0c5316caca.png)

![image](https://user-images.githubusercontent.com/36991769/99640667-3989ca00-2a6f-11eb-9854-655f4179a1e5.png)

**Comment by bhavya-plotx** [comment]
Ask him to try on the App and see what is the bPLOT balance. Most probably this is a MetaMask issue. 
![image](https://user-images.githubusercontent.com/73012963/99642958-20cee380-2a72-11eb-9757-657fcbd0abe5.png)
