### ISSUE TITLE
Positions not showing up in the markets page

### ISSUE THREAD

**Issue by Samagra-Dev** [plotx/smart-contracts#124]
0xe74B3696c6d93716ce01472125Be3b9C74aA378B
This address placed 500 PLOT predictions in both daily markets on 12th Dec, but couldn't see his/her positions on the markets page. They were visible on the leaderboard of the markets, but on the markets page, a " - " was displayed in the positions column

**Comment by venkateshsys** [comment]
@Samagra-Dev Is there any screenshot for this issue? This is not possible to check because the status of that market is **NOT LIVE**. 
Anyhow, I checked for all the users individually from API in another LIVE - Weekly market, data is fine.
