### ISSUE TITLE
Unable to Claim  Market Creation Rewards

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#126]
**Describe the bug**
Getting "Transaction Failed" when trying to Claim Market Creation Rewards. Tried hard refresh as well and other devices too. Still the same.

**To Reproduce**
1. Go to 'My Account'
2. Click claim on 'Market Creation Rewards'
3. Getting error as "Transaction Failed" Try Again.

**Screenshots**
![image](https://user-images.githubusercontent.com/36991769/102461704-c7f16b80-406e-11eb-9855-faecbcfb881b.png)

**Comment by ankit5902** [comment]
ETH Address: 0xe74b3696c6d93716ce01472125be3b9c74aa378b
Discord Username: Kwoz

**Comment by ankit5902** [comment]
@venkateshsys Please check the issue and let me know.

**Comment by venkateshsys** [comment]
@ankit5902 MarketCreationReward contract has less plots (661 PLOTs as of now) to claim 1052 PLOTs. Once Nitika mam send the PLOT tokens to the contract address, user will able to claim his/her rewards.

**Comment by ankit5902** [comment]
Okay, this issue is solved.
So, closing it.
