### ISSUE TITLE
Show name of currency in participation notification

### ISSUE THREAD

**Issue by nitika-goel** [plotx/smart-contracts#37]
**Describe the bug**
The notification does not state which market received a prediction.

**Expected behavior**
The notification should mention new prediction on ETH/USD or BTC/USD

**Screenshots**
![image](https://user-images.githubusercontent.com/33280614/96334603-aa644d80-108f-11eb-9c8f-196ad7073c0f.png)

**Comment by ankitnirwal** [comment]
addres name of market currency in participation notification @nitika-goel
