### ISSUE TITLE
Increase decimals precision of LeveragedParticipation in Leaderboadr View

### ISSUE THREAD

**Issue by udkreddySomish** [plotx/smart-contracts#39]
**Describe the bug**
User had participated with amount of 0.011 with a leverage of 1. So the leveraged amount will be around 0.002, but it is displayed as zero in leaderboard view page.

**To Reproduce**
1. Go to https://app.plotx.io/leaderboard/0xe300faea583e2ef1017b386ce47cb7177cd14cd3

**Expected behavior**
Leveraged asset should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/48582214/96334920-f6b08d00-1091-11eb-9054-32b90a9b6083.png)

**Comment by ankitnirwal** [comment]
This issue is resolved @udkreddySomish

**Comment by udkreddySomish** [comment]
@ankitnirwal The above issue was resolved but the leveraged participation of last record in below screenshot  is greater than the actual participation. I think there is some rounding off decimal precision issue.
![image](https://user-images.githubusercontent.com/48582214/96335857-21eaaa80-1099-11eb-9061-ee69cbc4353a.png)

**Comment by ankitnirwal** [comment]
this issue is resolve now @udkreddySomish
