### ISSUE TITLE
Negative pending amount and wrong return amount in the 'MY ACCOUNT' page

### ISSUE THREAD

**Issue by Samagra-Dev** [plotx/smart-contracts#44]
![image](https://user-images.githubusercontent.com/66849800/96339417-34bda900-10b2-11eb-8d62-aba2c90a2abc.png)

Address - 0xc8555668862f2c9c0123d7a65513e8b9a86f4159

**Comment by venkateshsys** [comment]
Issue has been resolved @udkreddySomish
