### ISSUE TITLE
Add popup to give more allowance

### ISSUE THREAD

**Issue by nitika-goel** [plotx/smart-contracts#48]
**Is your feature request related to a problem? Please describe.**
Currently, a player needs to approve PLOT every time he/she participates in a market. This results in more gas and tx hindrance

**Describe the solution you'd like**
Create a link under approve toggle in Live market prediction "Approve more"
Opena popup with text box to enter amount to be approved 
Approve button.
Some text should be there around what does approval mean.

**Comment by ankitnirwal** [comment]
Added popup to give more allowance @nitika-goel
