### ISSUE TITLE
only 'in-creation' tab is visible on BTC-USD market page.

### ISSUE THREAD

**Issue by ankitnirwal** [plotx/smart-contracts#49]
sometimes only 'in-creation' tab is visible on the BTC-USD market screen, there is no other 'in-settlement' and 'settled' tab visible until user hit the refresh button.
![IMG-20201018-WA0008](https://user-images.githubusercontent.com/61899399/96367084-588ff600-1169-11eb-9929-69425d84e847.jpg)

**Comment by bhavya-plotx** [comment]
Haven't seen this issue in a while. Will close this.
