### ISSUE TITLE
Market with no participation shows "in settlement" when it should be settled.  

### ISSUE THREAD

**Issue by bhavya-plotx** [plotx/smart-contracts#50]
![image](https://user-images.githubusercontent.com/73012963/96367053-28485780-1169-11eb-8284-866f4a1e6284.png)

5:30 Hourly Market with no participation is "In Settlement" when it should be settled by now. (Current time: 5:42)

It shouldn't even be in dispute as there is no participation, although if it needs to go in dispute then it needs to show that.

**Comment by bhavya-plotx** [comment]
Same issue with this one. 
![image](https://user-images.githubusercontent.com/73012963/96368481-a4469d80-1171-11eb-8863-3759d08180df.png)

**Comment by nitika-goel** [comment]
The issue has been fixed. Please keep a watch @bhavya-plotx and inform if issue persists or else close the issue.
