### ISSUE TITLE
Disable dispute button in case of 0 participation

### ISSUE THREAD

**Issue by nitika-goel** [plotx/smart-contracts#52]
**Describe the bug**
If 0 participants are there, the the dispute functionality does not work. But it looks confusing.

**Expected behavior**
Disable dispute button in case of 0 participants. Add text
"Please note markets with 0 participants cannot be disputed" 

Show only in markets with 0 participants

**Screenshots**

**Desktop (please complete the following information):**
 - Extension

**Smartphone (please complete the following information):**
 - Extension 

**Additional context**

**Comment by ankitnirwal** [comment]
done, closing this issue
