### ISSUE TITLE
Add Wallet Connect integration to liquidity.plotx.io

### ISSUE THREAD

**Issue by bhavya-plotx** [plotx/smart-contracts#53]
Users are unable to connect with MetaMask on mobile with liquidity.plotx.io. 

Need Wallet Connect integration like in app.plotx.io.

**Comment by venkateshsys** [comment]
Liquidity website has been updated with Wallet Connect integration @bhavya-plotx

**Comment by ankit5902** [comment]
Note : All test performed with iOS App.

✅  Wallet Connect working on Desktop Browser (Brave, Chrome, Firefox).
✅  Wallet Connect working on Mobile Browser (Brave, Chrome).
✅  Wallet Connect working on MetaMask Mobile dApp Browser with Trust Wallet.
✅  Wallet Connect working on Trust Wallet Mobile dApp Browser with MetaMask Mobile Wallet.
❌  Wallet Connect not working on MetaMask Mobile dApp Browser with MetaMask.
❌  Wallet Connect not working on Trust Wallet Mobile dApp Browser with Trust Wallet.

**Comment by ankitnirwal** [comment]
done, closing this issue
