### ISSUE TITLE
Button for raising dispute doesn’t work on mobile[Short description of bug]

### ISSUE THREAD

**Issue by TanishGanjoo** [plotx/smart-contracts#55]
The 08:00 bitcoin market needs disputing, clearly below $11450 was $11436 on Binance at 20:00 surely not that much difference.

What was the chain link price?
Button for raising dispute doesn’t work on mobile

It clearly takes the actual settlement price early.  Come on guys if we can’t get this right what hope have we got.  Everybody will be disputing results.  This is fundamental and wrong needs fixing as a matter of urgent

![image](https://user-images.githubusercontent.com/73099614/96420967-ce509c00-1213-11eb-91fa-32d014b4349d.png)

![image](https://user-images.githubusercontent.com/73099614/96421031-e6282000-1213-11eb-8030-428f3055b699.png)

![image](https://user-images.githubusercontent.com/73099614/96421049-eb856a80-1213-11eb-8b3b-f459c448adc3.png)

**Comment by ankitnirwal** [comment]
donr, closing this issue
