### ISSUE TITLE
Grammatical Error My Accounts page

### ISSUE THREAD

**Issue by divij-sood** [plotx/smart-contracts#70]
There is a grammatical error in the PlotX up under staking.  "you will start getting more number of positions for the same about."

It should read "you will start getting a greater number of positions for the same amount."

![image](https://user-images.githubusercontent.com/73034074/96694450-1c95a480-13a6-11eb-92d9-12e51beee27a.png)

**Comment by bhavya-plotx** [comment]
@ssl-surendra On Beta it shows me the wrong spelling only? Is it done? How to I verify? 
![image](https://user-images.githubusercontent.com/73012963/97030414-5ddfad00-157c-11eb-8a73-a01b3d13aa5e.png

**Comment by bhavya-plotx** [comment]
Close.
