### ISSUE TITLE
Leaderboard numbers are showing 0 participation & rewards

### ISSUE THREAD

**Issue by krakjack** [plotx/smart-contracts#74]
**Describe the bug**
The leaderboard numbers that show market participation data is showing null values

**To Reproduce**
1. Go to the leaderboard page
2. See error

**Expected behavior**
Amount of the ETH & PLOT staked + Rewards distributed should be updated in real-time

**Screenshots**
<img width="1023" alt="Screenshot 2020-10-22 at 1 13 24 PM" src="https://user-images.githubusercontent.com/30382982/96840665-61820f80-1468-11eb-8976-89fcfca3c043.png">

**Desktop (please complete the following information):**
 - Chrome Browser
 - Metamask Extension

**Comment by venkateshsys** [comment]
Issue has been resolved
![image](https://user-images.githubusercontent.com/48546261/96972111-b2126f00-1533-11eb-8db6-bf4cc38c2053.png)

**Comment by bhavya-plotx** [comment]
Resolved.
