### ISSUE TITLE
My account page is showing wrong numbers

### ISSUE THREAD

**Issue by bhavya-plotx** [plotx/smart-contracts#79]
https://files.slack.com/files-pri/T5UNTH4AF-F01D0LMCV0V/image.png
https://files.slack.com/files-pri/T5UNTH4AF-F01CP1HRFL7/image.png

**Comment by venkateshsys** [comment]
![image](https://user-images.githubusercontent.com/48546261/96971805-43351600-1533-11eb-885b-5570526b46a1.png)

**Comment by bhavya-plotx** [comment]
Resolved.
