### ISSUE TITLE
User is saying Markets he participated in are not showing

### ISSUE THREAD

**Issue by bhavya-plotx** [plotx/smart-contracts#80]
user: Dan3

Txn id:
https://etherscan.io/tx/0x59bd3758eed144295693683507bd4867b14d9e4b98709d9083e3b574afc4f79f
https://etherscan.io/tx/0x8873a1ce550a5ce339233d898b0636bbaae645b8a7d41d948f751779b526bf72

**Comment by venkateshsys** [comment]
Issue has been resolved
![image](https://user-images.githubusercontent.com/48546261/96971617-fd784d80-1532-11eb-8c2f-6a8900845563.png)
![image](https://user-images.githubusercontent.com/48546261/96971689-197bef00-1533-11eb-8eff-552f30e9cb4d.png)

**Comment by bhavya-plotx** [comment]
Resolved. Checked with user.
