### ISSUE TITLE
Error while executing contract transaction

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#82]
**Error while contract execution**
I was predicting on **What will be the value of ETH/USD at Oct 23 2020 12:30 pm ?** (IST). I received this error **"Warning! Error encountered during contract execution [Reverted]"** while executing the transaction.

**ETH Address :** 0x7Ba7f68AC3929a2357123440e2DB79d5e6767895

**Etherscan :** https://etherscan.io/tx/0x73a8dc51fbcf0d51227868e9e806c1e630b4a3afeb8ae845f3e6196464c3aa2b

**Screenshots**

![image](https://user-images.githubusercontent.com/36991769/96975687-6c0bda00-1538-11eb-91ec-b8f3bae03452.png)

**Comment by ankit5902** [comment]
Another same issue : https://etherscan.io/tx/0xabf65aab02548c7bc8450ada45093b19dfa0b5fdb78c4c2588469d3d030e0441

**Comment by udkreddySomish** [comment]
The prediction stake 10, as the option price was increased, no of positions value became too low(<0.01) which caused  the transaction to revert.
Need to add a check in UI, if number of positions expected is <=0.01 then we should not allow user to place prediction

**Comment by udkreddySomish** [comment]
@ankitnirwal Assigning this to you,
please add the check while placing prediction: `if number of positions expected is <=0.01 then we should not allow user to place prediction`

**Comment by ankitnirwal** [comment]
put the check, closing this issue now.
