### ISSUE TITLE
Participation incentives not showing in the market leaderboard screen

### ISSUE THREAD

**Issue by krakjack** [plotx/smart-contracts#85]
**Describe the bug**
Total participation incentives are shown as 0 despite multiple participants in the market

**To Reproduce**
1. Go to https://app.plotx.io/leaderboard/0xd9b07d4a863fb7bcb85a113da8703be513d38e36
2. See the Participation incentives field showing 0

**Expected behavior**
It should be showing 100 PLOT

**Screenshots**
<img width="1232" alt="Screenshot 2020-10-24 at 4 07 49 PM" src="https://user-images.githubusercontent.com/30382982/97079601-122c1280-1613-11eb-8fcd-415af52b0b7e.png">

**Comment by venkateshsys** [comment]
@krakjack  Incentives have not sent to this market, there is some bot issue while transferring incentives to this market: 0xd9b07d4a863fb7bcb85a113da8703be513d38e36

**Comment by venkateshsys** [comment]
@krakjack transaction hash for sending incentives is https://etherscan.io/tx/0x81d0e2852f2500f0e0653208853b19007cb82203c20f766169781fbfee755d0f.
Please refer to [this](https://docs.google.com/spreadsheets/d/1OcpX4cwtiOzkHFX3pCTOQ34YSntw0sKo4jvjK6Dl9fE/edit#gid=1649135026) sheet for more information of missing market incentives.
I will update this sheet if any further missing market incentives information.

**Comment by bhavya-plotx** [comment]
Closing this now.
