### ISSUE TITLE
Prediction bot doesn’t seem to be showing the correct values

### ISSUE THREAD

**Issue by bhavya-plotx** [plotx/smart-contracts#87]
![image](https://user-images.githubusercontent.com/73012963/97088231-1e34c600-164d-11eb-9d2e-74c8876db019.png)

**Comment by venkateshsys** [comment]
What is the market address of BTC/USD @bhavya-plotx

**Comment by bhavya-plotx** [comment]
@venkateshsys 
![image](https://user-images.githubusercontent.com/73012963/97144372-5392fe00-178a-11eb-8fb2-17d4a50375a3.png)

Please see the timestamp (IST) on the message and the date (24th) 🙏

**Comment by venkateshsys** [comment]
@bhavya-plotx the data in the database is perfect for this market address: **0xeabf79e132d13434917f4e5340b3115c3f514571**
I think Kushal was fetching the info earlier than the database update.

**Comment by bhavya-plotx** [comment]
Closing this now.
