### ISSUE TITLE
Participation incentives not showing in the market leaderboard screen

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#90]
**Describe the bug**
Total participation incentives are shown as 0 despite a participant in the market. Also the user hasn't received the participation incentives..

Telegram : @Sha256ma

User ETH Address : 0x1bcd0f272c97593597c2d35a351b0b875ee16092

**Steps to reproduce the behaviour :**
Go to https://app.plotx.io/leaderboard/0x9cfd73ecae7f90485198e4ec7ca813913487cb4b
See the Participation Incentives field showing 0

**Expected behaviour :**
It should be showing 100 PLOT

**Screenshots :**

![IMAGE 2020-10-25 15:36:22](https://user-images.githubusercontent.com/36991769/97104179-dad36980-16d7-11eb-8f89-1b70e3f22efe.jpg)

**Additional Comments :**
A similar thread with the same issue on Github : https://github.com/plotx/smart-contracts/issues/85

**Comment by venkateshsys** [comment]
@ankit5902 Incentives have not sent to this market, there is some bot issue while transferring incentives to this market: 0x9cfd73ecae7f90485198e4ec7ca813913487cb4b. We have to manually send the calculated incentive rewards to all participants

**Comment by ankit5902** [comment]
Okay, please update when it is sent.

**Comment by ankit5902** [comment]
Participation Incentive sent to User (@Sha256ma).
