### ISSUE TITLE
Duplicate participation rows for BTC USD Market

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#92]
**Total Pool Amount in Leaderboard is incorrect**
Total Pool Amount for BTC/USD Market is incorrect

**To Reproduce**
1. Go to 'https://app.plotx.io/leaderboard/0xe4320ad5a58d2477dd5bd8b122a0cf1ffad2a9b9'
2. The Total Pool Amount is incorrectly calculated. 

**Expected behavior**
It should show 130 PLOT but it's showing only 90 PLOT

**Screenshots**

![Screenshot 2020-10-25 at 9 38 36 PM](https://user-images.githubusercontent.com/36991769/97112674-ac6f8180-170b-11eb-93e8-e68531a1a11a.png)

**Comment by venkateshsys** [comment]
@ankit5902. Actual issue is Duplicate participation rows in BTC/USD market. Now, the issue has been resolved.

![image](https://user-images.githubusercontent.com/48546261/97113765-80a3ca00-1712-11eb-8991-5a00aa5ac156.png)

**Comment by ankit5902** [comment]
Okay. Thank you..
