### ISSUE TITLE
Feature request of sharing the Leaderboard/Market from app.plotx.io to Social Handles

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#95]
**Feature request on app.plotx.io**
Suggestion by **Telegram User @Wreathy** : "Would be cool if you could integrate a click n copy leaderboard trades, ppl could follow comment maybe tie it into socials etc"

**Additional context**
A share button on Leaderboard to share on social handles like we share something on Twitter, FB, Insta, TG etc..

**Comment by ankitnirwal** [comment]
done, closing this issue
