### ISSUE TITLE
Rewards shown in Claim for the Markets in Cooling period is not actually claimable until Settled

### ISSUE THREAD

**Issue by ankit5902** [plotx/smart-contracts#97]
**Describe the bug**
"At the moment rewards that are shown as claimable during the "Cooling" period when in reality they aren't actually available to claim until the market has settled. Could this please be updated as it is misleading and users, such as myself, may waste gas trying to claim rewards too early."

**Discord :** @fraser.clay, @Icon470

**To Reproduce**
1. Go to 'My Account'
2. Click on 'Claim'
3. The rewards for the markets which are in Cooling period is shown in Claim, but actually it isn't claimable.

**Additional Comments**
Maybe we can do something is not to include the rewards in claim until the Market is settled. So as to avoid creating confusion.

**Comment by venkateshsys** [comment]
API has been updated. @ankit5902
