### ISSUE TITLE
Negative pending amount

### ISSUE THREAD

**Issue by Samagra-Dev** [plotx/smart-contracts#99]
"I've now claimed my win but it seems very low and leaves me with an amount of -91.3807 PLOT sitting in pending?

Can you explain to me please as it appears it cost more in gas than i won and i don't understand the negative value in Pending.

Thanks"

The above is how the user described the issue. After doing L1 check, it seems to be a UI glitch. Here is a screenshot of the same.
User address - 0x1E6ac7ef902913c3546813eA3EE06Eed36C356D9

![image](https://user-images.githubusercontent.com/66849800/97775191-d1894780-1b84-11eb-9376-4f7fa1e39eb8.png)

**Comment by venkateshsys** [comment]
@Samagra-Dev @bhavya-plotx 
Resolved the DB sync issue. Please confirm with the user and close it.

![image](https://user-images.githubusercontent.com/48546261/97810392-81e87000-1c99-11eb-8c4d-5e5bcc16a251.png)
